name: Build image on commit to master

on:
  push:
    branches:
      - 'release-*' # Codefresh change instead of `master`

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/work/applicationset
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16.2'
      - uses: actions/checkout@master
        with:
          path: src/applicationset

      # Build the image
      - run: |
          docker images -a --format "{{.ID}}" | xargs -I {} docker rmi {}
          CONTAINER_REGISTRY=quay.io IMAGE_NAMESPACE=codefresh IMAGE_TAG=latest make image
        working-directory: ./src/applicationset
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}


      # Publish the image
      - run: |
          docker login quay.io --username $QUAY_USERNAME --password $QUAY_TOKEN
          docker push quay.io/codefresh/applicationset:latest
        env:
          QUAY_USERNAME: ${{ secrets.RELEASE_QUAY_USERNAME }}
          QUAY_TOKEN: ${{ secrets.RELEASE_QUAY_TOKEN }}
